// scripts/build-kb.js
// Concatenates all reference + help MDs into a single JS module
// that the Cloudflare Worker imports for fast cold-start.
//
// Run: node scripts/build-kb.js
// Output: functions/api/_kb.js (auto-generated, do not edit by hand)

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..');
const OUT_FILE = path.join(REPO_ROOT, 'functions', 'api', '_kb.js');

const SOURCES = [
  'reference/workflows.md',
  'reference/categories-to-buyers.md',
  'reference/smart-forms.md',
  'reference/operational-rules.md',
  'reference/quote-thresholds.md',
  'reference/timeline.md',
  'reference/glossary-brnet-vs-ananet.md',
  'help/where-to-go.md',
  'help/known-issues.md',
  'help/support-channels.md',
];

let kb = '';
for (const rel of SOURCES) {
  const full = path.join(REPO_ROOT, rel);
  if (!fs.existsSync(full)) {
    console.warn('Skip (missing):', rel);
    continue;
  }
  const content = fs.readFileSync(full, 'utf8');
  kb += `\n\n## ${rel}\n\n${content}\n\n---\n`;
}

const safe = kb.replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
const moduleSrc = `// AUTO-GENERATED by scripts/build-kb.js — do not edit by hand
export const KB = \`${safe}\`;
export const KB_SOURCES = ${JSON.stringify(SOURCES, null, 2)};
export const KB_LENGTH = ${kb.length};
`;

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, moduleSrc, 'utf8');

console.log('Built KB:', kb.length, 'chars from', SOURCES.length, 'files');
console.log('Output:', OUT_FILE);
